#!/bin/bash

# get directory of this file as source directory
pushd $( dirname $0 ) >/dev/null
srcdir=$( pwd )
popd >/dev/null

targetdir=$HOME/.config/nvim
mkdir -p $targetdir

ln -sf $srcdir/init.vim $targetdir/init.vim
ln -sf $srcdir/mappings.vim $targetdir/mappings.vim
ln -sf $srcdir/plugins.vim $targetdir/plugins.vim

