#!/bin/bash

# get directory of this file as source directory
pushd $( dirname $0 ) >/dev/null
srcdir=$( pwd )
popd >/dev/null

targetdir=$HOME/.config/gtk-3.0

ln -sf $srcdir/gtk.css $targetdir/gtk.css

