#!/bin/bash

# get directory of this file as source directory
pushd $( dirname $0 ) >/dev/null
srcdir=$( pwd )
popd >/dev/null

targetdir=$HOME/.config/redshift
mkdir -p $targetdir

ln -sf $srcdir/redshift.conf $targetdir/redshift.conf

